### PR TITLE
accessibility fix

### LINKED ISSUE #420: [A11y] Calendar picker has no discernable text
1. Navigate to: https://tempnewsroom.accenture.com/
2. Check the Calendar filter field

ER: ara-label is present with the value like "Select a date"
AR:  aria-label was not present

To solve this problem, you need to fix at least (1) of the following:
- Element has a value attribute and the value attribute is empty
- Element has an empty value attribute
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element has no title attribute
- Element's default semantics were not overridden with role="none" or role="presentation"

### PR DESCRIPTION
**Pull request by amol-anand**
Fix #420 

Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.live/
- After: https://accessibility-improvement--accenture-newsroom--hlxsites.hlx.live/

### CODE REVIEW

File: blocks/newslist/newslist.js [hunk 1]
```diff
@@ -490,7 +490,7 @@ export default async function decorate(block) {
           <span class="newslist-filter-arrow"></span>
         </label>
         <input type="text" id="newslist-filter-input" title="${pDateRange}" name="date" value="" size="40" placeholder="${pDateRange}" maxlength="60" disabled>
-        <input type="submit" value="" disabled>
+        <input type="submit" value="" aria-label="calendar" disabled>
```
Comment (ravkiran) [inline blocks/newslist/newslist.js:493]: but the actual widget is the input (text) above right?
should we put the label on the submit?

Comment (amol-anand) [reply blocks/newslist/newslist.js:493]: Screenshot 2023-11-03 at 5 35 31 PM

PSI complaining about this.
