### PR TITLE
149669 date trans

### LINKED ISSUE #239: 149669 - [Newsroom] Newsfeed- Date is not translated and formated in Newscard in all local geos [de, fr, it, pt, sg, jp, es]
**Severity  3 - Medium**

Steps to Reproduce: 
1. Open URL migrated and legacy newsroom page for local geo
2. Navigate to the cards

Actual: Date format is different for all local geo and is not translated.
image

Expected: Date should be translated and formated
image

Migrated pages:
https://main--accenture-newsroom-de--hlxsites.hlx.live/
https://main--accenture-newsroom-br--hlxsites.hlx.live/
https://main--accenture-newsroom-it--hlxsites.hlx.live/
https://main--accenture-newsroom-uk--hlxsites.hlx.live/
https://main--accenture-newsroom-sg--hlxsites.hlx.live/
https://main--accenture-newsroom-pt--hlxsites.hlx.live/
https://main--accenture-newsroom-jp--hlxsites.hlx.live/
https://main--accenture-newsroom-fr--hlxsites.hlx.live/
https://main--accenture-newsroom-es--hlxsites.hlx.live/

Legacy Newsroom pages:
https://newsroom.accenture.jp/
https://newsroom.accenture.de/
https://newsroom.accenture.fr/
https://newsroom.accenture.it/
https://newsroom.accenture.es/
https://newsroom.accenture.co.uk/
https://newsroom.accenture.sg/
https://newsroom.accenture.pt/
https://newsroom.accenturebr.com/

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/149669
cc: @ravkiran @amol-anand @raymond-h-dev

### PR DESCRIPTION
**Pull request by veejayricana**
Fix the date translation in local geo <BR>. Remove the extra word (DE) in the translation.

Fix #239 

Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/
- After: https://149669-date-trans--accenture-newsroom--hlxsites.hlx.page/

### CODE REVIEW

**Comment by veejayricana** [comment]
Sorry @ravkiran, I comment wrong local geo, but it is PT there an extra word DE in the date translation and for ES you use SP in country selector but I us in my date translator ES. This is reason why is there is no date in the news card.
franklin:
image
legacy:
image

File: blocks/newslist/newslist.js [hunk 1]
```diff
@@ -37,12 +37,13 @@ function getHumanReadableDate(dateString) {
...
   // display the date in GMT timezone
   const country = getCountry();
-  return date.toLocaleDateString(getDateLocales(country), {
+  const localedate = date.toLocaleDateString(getDateLocales(country), {
     timeZone: 'GMT',
     year: 'numeric',
     month: 'long',
     day: '2-digit',
   });
+  return localedate.replace(/de/g, '');
```
Comment (ravkiran) [inline blocks/newslist/newslist.js:46]: @veejayricana looks like `de` means `of` in pt. Rather than just replacing this for every locale, can you add a condition like 
```
if (country.includes['pt', 'br']) {
   // de means of in pt/br, replacing with empty string
   localedate.replace(/de/g, '');
}
```
